### ISSUE TITLE
Question on pred_length and gt_lenght

### ISSUE THREAD

**Issue by cheliu-computation** [MAGIC-AI4Med/RaTEScore#1]
In the usage part, it mentions the length of pred_report must be equal to gt_report.
But during real case, the gt_report length is various, and the pred_report from LLM is also diverse.
Does it mean RaTEScore only work with the report with the same length?
If it is, how to process the report to make the same length but do not divert the semantics?

## Usage

```python
from RaTEScore import RaTEScore

pred_report = ['There are no intracranial hemorrhages.',
              'The musculature and soft tissues are intact.']

gt_report = ['There is no finding to suggest intracranial hemorrhage.',
            'The muscle compartments are intact.']

assert len(pred_report) == len(gt_report)

ratescore = RaTEScore()
# Add visualization_path here if you want to save the visualization result
# ratescore = RaTEScore(visualization_path = '')

scores = ratescore.compute_score(pred_report, gt_report)
```

**Comment by Angelakeke** [comment]
Hi,
It seems there might be a misunderstanding regarding the term "length." 
Here, the length of reports refers to the number of reports that you want to evalutate, which should be certainly at the same length. Each report can consist of multiple sentences.

Best,
Weike

**Comment by cheliu-computation** [comment]
Thanks! I have misunderstood the code.
Now it is clear for me.
